### ISSUE TITLE
Minimal-server occupancy.ttl is invalid 

### ISSUE THREAD

**Issue by timothy-debock** [Informatievlaanderen/VSDS-Onboarding-Example#14]
https://github.com/Informatievlaanderen/VSDS-Onboarding-Example/blob/main/minimal-server/definitions/occupancy.ttl is an invalid ttl file -> Expected declaration to end with a dot on line 8.

`@prefix : 			 <https://example.org/ns/mobility#>`

This line shoult end with a period.
`@prefix : 			 <https://example.org/ns/mobility#> .`

**Comment by rorlic** [comment]
Thank you!
In fact, the whole line is not needed and was removed meanwhile.
