### ISSUE TITLE
Migrate to v3

### ISSUE THREAD

**Issue by MPParsley** [Informatievlaanderen/VSDS-Onboarding-Example#24]
Still in alpha but would be nice if the examples were ready for v3.

cf. https://github.com/Informatievlaanderen/VSDS-LDESServer4J/releases/tag/v3.0.0-alpha

**Comment by rorlic** [comment]
All examples now use the reference images:
* [LDES Server 3.6.1](https://hub.docker.com/r/ldes/ldes-server/tags?name=3.6.1)
* [LDIO Workbench 2.12.0](https://hub.docker.com/r/ldes/ldi-orchestrator/tags?name=2.12.0)
