### ISSUE TITLE
./definitions/occupancy.ttl is not valid

### ISSUE THREAD

**Issue by mirchat** [Informatievlaanderen/VSDS-Onboarding-Example#7]
I am using the main branch, the readme makes reference to some content of occupancy.ttl that does not exist.

Indeed, when I run the command, I get an error
curl -X POST -H "content-type: text/turtle" "http://localhost:9003/admin/api/v1/eventstreams" -d "@./definitions/occupancy.ttl"
Warning: Couldn't read data from file "./definitions/occupancy.ttl", this
Warning: makes an empty POST.

**Comment by rorlic** [comment]
Which tutorial are you running?
Please ensure to change your directory to that location. For example if you are looking at the [Setting up a minimal LDES Server](./minimal-server/README.md) tutorial, please open a bash shell at that location or `cd ./minimal-server` before running the commands, incl curl.

**Comment by mirchat** [comment]
apologies, I run to hide in shame for opening this bug
